---
- name: serverspec - Create directories
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop:
    '{{ directories }}'

- name: serverspec - Installing dependencies on Debian/Ubuntu
  apt: 
    name: {{ item }} 
    state: latest
  with_items:
    - ruby
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: serverspec - Installing dependencies on CentOS/RedHat
  yum: 
    name: {{ item }} 
    state: latest
  with_items:
    - ruby
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Centos - Install serverspec latest version
  community.general.gem:
    name: serverspec
    state: latest
    user_install: false
